apiVersion: v1
kind: Namespace
metadata:
  namespace: test
  annotations:
    iam.amazonaws.com/allowed-roles: |
<<<<<<< HEAD
      ["approved ARN here"]
=======
      ["replace with S3 ARN"]
>>>>>>> upstream/master
  name: test